#! /bin/sh

# Install RPMs from Bodhi update before they are in updates-testing
# Copyright (C) 2020 Red Hat Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

die() { echo >&2 "$*" ; exit 1; }

case $1 in
    *-*-*) ;;
    *) die "Please use a valid first argument, e.g. FEDORA-2020-518278a39e" ;;
esac

update=$1

workdir=$(mktemp -d /tmp/fedora-early-testing-XXXXXX)
echo >&2 "Working in a temporary directory $workdir"
cd "$workdir"

echo >&2
echo >&2 "===="
echo >&2 "Going to disable GPG check for the tested packages!  Stop me now!"
echo >&2 "===="
echo >&2
sleep 3

bodhi updates download --updateid "$update"
createrepo_c .

sudo dnf update --enablerepo local-bodhi-update \
                --repofrompath "local-bodhi-update,$workdir" \
                --setopt=local-bodhi-update.gpgcheck=0
